// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM17_z7KV6QHjUNHRtnUO4x7jnHEF4UiI',
    appId: '1:915405090420:web:aaf0bf6d56c116c54ceb21',
    messagingSenderId: '915405090420',
    projectId: 'spectrumspeak2024',
    authDomain: 'spectrumspeak2024.firebaseapp.com',
    storageBucket: 'spectrumspeak2024.appspot.com',
    measurementId: 'G-NXP6YFRRT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7SGYbg45QIrkifhhwYx5RT8Lgo4odFlg',
    appId: '1:915405090420:android:17f9c9846935c2994ceb21',
    messagingSenderId: '915405090420',
    projectId: 'spectrumspeak2024',
    storageBucket: 'spectrumspeak2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0JFNNhcaPpwxOQeFTDjZUK6WzhiH7cc',
    appId: '1:915405090420:ios:8816e4dc032440854ceb21',
    messagingSenderId: '915405090420',
    projectId: 'spectrumspeak2024',
    storageBucket: 'spectrumspeak2024.appspot.com',
    iosBundleId: 'com.example.spectrumSpeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0JFNNhcaPpwxOQeFTDjZUK6WzhiH7cc',
    appId: '1:915405090420:ios:7154a8faf32c42484ceb21',
    messagingSenderId: '915405090420',
    projectId: 'spectrumspeak2024',
    storageBucket: 'spectrumspeak2024.appspot.com',
    iosBundleId: 'com.example.spectrumSpeak.RunnerTests',
  );
}
